utilisateurs:
    resource: "@UtilisateursBundle/Controller/"
    type:     annotation
    prefix:   /

store:
    resource: "@StoreBundle/Controller/"
    type:     annotation
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"